pdf:
	/usr/bin/pandoc ./00.forematter.md --to latex \
		--from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash \
		--output ../../report.gnr/07.iccss2015.pdf \
		--template /home/abaghan/R/x86_64-pc-linux-gnu-library/3.1/rmarkdown/rmd/latex/default.tex \
		--highlight-style tango --latex-engine pdflatex \
		--include-in-header header.tex --variable 'geometry:margin=1in'
