# Research Design

## Data and variables

The data for our study came from a Spanish survey on habits and cultural
practices for 2006-2007 (see Ministry of Culture (2007) for technical details).
Surveyed were 14 822 Spanish and non-Spanish individuals of both sexes, aged 15
years and older, and resident in Spain at the time of interview. The survey was
conducted in four waves (1 per quarter) between March 2006 and February 2007;
each quarterly survey was based on a representative random sample of about 25%
of the sampled individuals (all four quarterly surveys were used for our
analysis), stratified by autonomous communities and municipalities according to
size. Stratification by autonomous community was necessary to produce a
representative sample with a 95% confidence level, not only at an aggregate
level (age and gender) but also at the autonomous community level (Ministry of
Culture, 2007:11). In the interest of brevity, background data referring to the
research described below are provided in supplementary form in Tables A1-A6.

### Cultural space: musical listening indicators

Individuals interviewed were asked about the kind of music he/she normally
listen to.  Individuls were given a list of musical genres and they just had to
choose the ones they usually listen to. The following multiple answers (21 in
total) were possible: songs for children (chl), songwriters (swr), ballads
(bls), flamenco (flk),  new flamenco (nfl), other spanish folk songs (flk),
international pop rock (ipp), Spanihs poprock (spp), latino poprock (lpp),
blues (bls), jazz (jzz), world music (wrl), reggea (rgg), rap (rap), electronic
music and techno (tcn), hardrock (hrk), house (hus), classical music (cls),
Lyrical music (lyr), opera (opr), operetta (opt). Desciptors are provided in
Table~\ref{tab:stat.genres}. 

### Social space: indicators of individual position

According to Bourdieu???s theoretical framework, the properties of individuals
are indicators of their social position, such that variations in individual
properties ??? level and structure of capital, age, gender, etc. ??? are
variations in the individual???s social position that are visible in a social
map. The Ministry of Culture survey on which we based our research elicited
information on education as an indicator of cultural capital, and on
occupational status as an indicator of economic capital, but provided no
occupational breakdown, and collected no information on incomes. As a proxy for
economic capital in our study, therefore, we used occupational status,  namely,
the following five categories: employed persons; entrepreneurs and
self-employed workers (freelancers); unemployed persons; people receiving
old-age or disability pensions and individuals performing unpaid domestic tasks
(homemakers); and students. Educational attainment was recorded in three
categories, as follows: third-level post-graduate education, third-level
graduate education, and upper secondary education or below. Age, interpreted
here as an indicator of an individual???s life stage, was assigned to five
categories. In order to complete the description of the social space, four
additional variables were included, as follows: personal situation (five
categories); number of individuals aged 15 and over in the household (three
categories); habitat where the household was located (five categories); and sex
(Table~\ref{tab:stat.descriptors}).

## Analysis

### Uncovering the music schemes 

#### Correlation Classification Analysis

To uncover and measure shared music schemas in survey data we used Correlation
Classification Analysis (CCA) developed by Andrei Boutyline (2014) ???. CCA is
based on Relational Class Analysis (RCA), a novel methodology with the aim of
measuring shared cultural schemas developed by @goldberg2011mapping
\cite{goldberg2011mapping}. At the core [@goldberg2011mapping]
of RCA approach is a novel similarity measure termed *relationality* which in
CCA approach is changed into a Pearson correlation measurement termed
*correlation class*. Boutyline contends that correlationality (i.e. the level of
pairwise correlations) can quantify the extent to which two respondents organize
their attitudes according to such a shared cultural schema more accurately and
technically faster than RCA.

CCA calculates the Pearson correlation scores for each pair of respondents and
uses the result matrix to construct and value the links of a network in which
nodes are individual survey respondents. Then the method drops waker ties,
partitions the network via Newman's (2006) eigenvector-based modularity
maximization algorithm to assign individuals to groups the way that  correlation
scores are high within groups, and lower between groups.

#### Multiple Correspondence Analysis

To test our theoretical framework, we needed an instrument capable of analyzing
two related spaces: that of individuals and that of Internet use. Like Bourdieu
in La Distinction (1984), we used the multiple correspondence analysis (MCA)
technique (Greenacre, 1993; Greenacre & Blasius, 1994; Lebart, Morineau, &
Warwick, 1984); in particular, we used the implementation of MCA by Ven- ables
and Ripley (2002, pp. 329–330). The MCA enabled us to build up the Internet use
and indi- vidual spaces from a set of uses large enough to allow a full
multidimensional display of individuals (Rouanet, Ackermann, & Le Roux, 2004).
How individuals were related to their Internet use patterns revealed their
linkages with other individuals. A geometric representation of the Internet use
space is as simple as diagonalizing an n-by-l matrix G of n individuals (rows)
observed for p Internet use (dummy variables) with l (1⁄4 p Â 2) total cate-
gory levels (columns). 

A simple geometric display consists of a two-dimensional space where 

Inter- net
use and use level are plotted according to their association with each of these
dimensions. The result is an asymmetric row plot of the matrix of individuals
according to Internet use. To interpret the social space constructed in this
way, we used the inertias (total variance) of the principal axes and the
contributions of the Internet use categories to the axes (see Ambrogi,
Biganzoli, & Boracchi, 2005). MCA enables active variables to be distinguished
from supplementary properties, with the latter term used to define variables
that have no impact on the geometric orienta- tion of the dimensions but which
may help with interpretation (Greenacre, 1993). In our research, we used MCA
both as an exploratory and explanatory tool; for the latter, we used the
‘‘predict’’ method for the ‘‘MCA’’ class implemented in the Modern Applied
Statistics with S (MASS) package (Venables & Ripley, 2002), using the R language
and environment for statistical analysis, version 2.9.0 (R Development Core
Team, 2009).

### Interpreting the music schemes
