---
title: 'Young People’s Leisure Patterns: Testing Social Age, Social Gender and Linguistic Capital Hypothesis'
author: "Jordi López Sintas, Abaghan Ghahraman, Elena Pérez-Rubiales"
date: January 2015
abstract: "We are interested in analyzing the patterns of leisure activities
conducted by young individuals in order to identify and describe
age-differentiated and socially recognized patterns of leisure activities. In
the theoretical framework we argue that the effect of the main social categories
that structure young individuals leisure patterns might be mediated by
individuals' social positions. The effect of this proposition challenges recent
finding that proposes that social position indicators structures leisure
patterns orthogonally to age. We have found that leisure practices can be
classified around three leisure habitus: 1) the habitus of doing leisure
activities, 2) the habitus con doing cultural activities, and 3) the habitus of
conducting social or entertainment activities. Young people leisure habitus can
be classified into four patterns of leisure: a social pattern, a
cultural/omnivours pattern, an entertainment pattern, a religious pattern. The
association of leisure patterns to the social categories suggests that when we
take into account the mediating role of social position indicators on the main
social categories, the main effect age, gender, and linguistic habitus vanishes,
as predicted by the *social age hypothesis*, the *social gender hypothesis*, and
the linguistic capital hypothesis. That is, young people do not form an
homogeneous social category, but  their leisure practices are still socially
differentiated, placing specially young people immigrants into a disadvantage
position."
output:
  word_document: default
  pdf_document:
    toc: yes
---

# Introduction

During the transition from adolescence to adulthood, in their social context, young individuals learn  the behavior that their family and peers expect of individuals holding concrete positions in the social structure (George 1993). The processes by which roles are assigned to individuals are experienced, first, at home and from relatives, and, secondly, when interacting with their peers in a wider social context (Pronovost 2009; Tolonen 2013). All this process is named  the socialization process by which young people learn the skills and attitudes compatibles with the social roles assigned to them in the process of  becoming an adult (Pollock 2008).

The life course of young people, then, reflects the intersection of their social factors as well as the historical moments lived with their personal biography (Elder 1985 ???), hence life courses  are expected to vary across time, space and populations. Although in this piece of research we are not interested in the sequences of transitions of concrete individuals (Kuehn 2000) or cohorts of young people (Bynner 2012; Wyn & Woodman 2006), we are interested in studying the patterns of leisure activities conducted by young individuals in order to identify and describe age-differentiated and socially recognized patterns of leisure activities. 

Recent research has suggested that the composition and volume of individual's capital (Bourdieu 1979; Peterson & Kern 1992 ???) as well as age are the main structuring factors of the cultural space (Tampubolon 2008a and b; López et al. 2014) and that the latter structure cultural tastes orthogonally to the indicators of capital. How ever, Bourdieu’s social age hypothesis as well as the studies into the leisure of young people between indicates the existence of an interaction among gender, biological age, and social class of parents that would challenge the independence between biological age and social position (Zeijl et al 2000; Tolonen 2013). Researchers of young people leisure patterns have concluded that the current set of leisure opportunities is not equally accessible to everyone, that leisure activities of contemporary young people continues to be structured mainly by the indicators of social position that interacts with gender and ethnicity (Shildrick & MacDonald 2006; Tolonen 2013; Zeijl et al. 2001). 

How ever, to which extent young people leisure patterns are structured by social factors, historical moments and cultural contexts is empirical matter (Birchwood, Roberts & Pollock 2008).  Even more,  some the study of young people leisure patterns provides an ideal oportonity to reexamine the relevance of current theories and the relevance of the new social theories (Shildrick et al. 2009). We will test theories with data from Catalonia, and autonomous region of Spain. This social setting is specially interesting to conduct research because: 1) the current historical moment characterized by high levels of unemployment as well small or even negative rates of wealth creation, and 2)  the fact that 25% of its young population comes from immigrant families. 

In this research we are interested identifying and measuring young people leisure habitus, the leisure patterns of young individuals according to their leisure habitus, and then 1) test whether ordinary social categories structure young people leisure patterns, and 2)  test whether the social age, social gender, and linguistic capital hypothesis qualify the effect of ordinary social categories on leisure patterns.

#The stratification of leisure

Since Bourdieu (1979) groundbreaking monograph, *La Distinction*, published in English in 1984, the sociology of culture has been interested in interpreting the relationship between the social space and the space of cultural habits. Bourdieu (1979/1984) has developed a social theory of cultural practices grounded on the data he gathered about the French in the 70s. His theory proposed the existence of an homology between the social  and the cultural spaces that describe individuals lifestyles.  Making use of Geometrical Data Analysis methods, concretely multiple correspondence analysis, MCA, he developed a cultural space of French lifestyles. He found the space to be structured by three dimensions that he named habitus. When he plotted the indicators of social position on the cultural space, he found that the indicators of capital composition (economic versus cultural) were associated to the first dimension; the indicators capital volume, to the second dimension--both dimensions formed the structural approach to social life--, and the indicators of life trajectories were associated to the third dimension--signaling the individual’s capacity of agency. He concluded that the cultural lifestyles of the French were related to their social position through their habitus--cognitive mechanisms of appreciation and action. The habitus, them, were hold by individuals only as long as they would hold the social position associated to the habitus. As a consequence, individuals that would change their social position would, as well, change their habitus. To what extent? It depends, according to Bourdieu's theory, on individuals' social trajectories (the transition from one social position to another).

This homology between the social  and the cultural spaces through the habitus has been interpreted as evidence of the Highbrow/popular culture distinction among privileged classes and the disadvantaged. Then, positions in the cultural space have been interpreted as cultural expressions of social positions, as expressions of the value of individuals occupying social positions, of distinctiveness or of necessity, depending on the social position. Individuals in  privileged social positions use cultural differences as expressions of differences in social value, as a legitimation of a ‘natural’, even though social, hierarchy of social value. This process of legitimation has been called symbolic violence, and it is based on markers of cultural capital, as the academic qualifications provided by the educational system, among others. In consequence, Bourdieu (1984) has suggested that social mobility and social reproduction is mediated by the school based system of accreditation (Nagel 2010; Pugh 2011; Emmison 2003; Daeneki & Roose 2014).

However, these univorous patterns of tastes and behaviors--highbrow for the privileged, popular taste for the disadvantaged--have been challenged since Peterson showed that individuals occupying privileged social positions exhibited an omnivorous pattern of musical tastes (Peterson and Simkus 1992 ???). Peterson proposed that even though he had found evidence in favor of the  homology thesis, the relationship between the social space and the space of cultural lifestyles showed an omnivorous pattern of tastes for the privileged social positions, and two univorous patterns for the other people--whether the univorous pattern was formed of a highbrow taste or a popular one, depended on the social position hold by the individuals. Peterson thesis found evidence in later works grounded on US data or non-US data (see Peterson 2004 ??? for a review). 

Since then, research has focused its attention on the relations of social class indicators with the space of culture. Although Bourdieu’s homology thesis has been contested (Chan & Goldthorpe 2007a,b) due to differences in research methodologies (Peterson 2007; Wuggenig 2007) or in the meaning of cultural indicators used in research (Bennett et al. 2008), findings describe Bourdieu's social homology, but with an omnivorous/univorous pattern: the indicators of a privileged social position are positively related to the established taste (Reeves 2014), but when the indicator of age is introduced in the analysis, the latter is positively related to contemporary taste (van Eijck 2001; López & García 2002a,b; Coulangeon 2003). In fact findings suggest that the composition and volume of capital as well as age are the main structuring factors of the cultural space. Even more findings suggest that age structure cultural tastes orthogonally to the indicators of capital (Tampubolon 2008a and 2008b; López et al. 2014). Similar findings have been reported for different cultural spaces and countries (Purhonen et al 2009; Savage 2006).  

Even though researchers do not agree about the right indicators for testing the homology hypothesis (Peterson 2004), most research have found evidence about the omnivorous thesis using different sets of cultural indicators. Current research designs have used indicators of both, participation in the arts as well as cultural tastes in contemporary Britain, UK (Le Roux et al. 2008) and in Flanders, Belgium (Roose et al. 2012). Their findings show that the space of culture is structured first by a predisposition towards cultural engagement--involvement versus disengagement--, and second by cultural taste--a taste for the established versus and emergent taste. When analyzing the correlation among the indicators of social position and the cultural space, they found that cultural engagement was related to the indicators of economic and cultural capital, and the cultural taste to age. The Omnivorous pattern is usually associated to young and privileged individuals (Virtanen 2005).  

Research, however, implicitly acknowledges that the effect of a social position on the habitus of individuals holding it does not interact with age. Yet, Bourdieu (1984) warns us about the differences concerning the biological and social age. He suggests that some individuals get early into the labor market occupying, then, an underprivileged social position (in terms of capital’s volume and composition) and developing the habitus of an older individual. The *social age hypothesis*, then, suggests that the effect of the biological age on the young individual's patterns of behavior depends on its social position, his and his parents. That is, individuals occupy social positions defined by a set of indicators: a young individual holding a privileged social position will develop an habitus (a long adolescence, for instance) different from the habitus of a young individual holding an underprivileged position (almost without adolescence). To test the *biological age hypothesis* against the *social age hypothesis*, we need to find evidence that the relationship between age and young people leisure patterns is mediated by their social position. 

Probably, Bourdieu argues, the fact that young people from underprivileged social positions have increased their participation in secondary education has produced the illusion that young people form an homogeneous social category. In France, in 1951 only 5,3% of the young people that could hold a high secondary diploma held it, but in  2001 it was the 66% (Hersent 2003:15 ???). As young people remain more time in the educational system, and living at their parents' home, it is more probable that underprivileged individuals will discover the temporal status of a long adolescence and will develop an habitus similar to the habitus of other young people holding privileged social positions. This fact produces the illusion of young people being homogeneous. 

If Bourdieu (1984) proposition is true, then we should find that the lifestyles of young individuals will differ only after certain age, but be similar below it. In fact, Zeijl et al. (2001), when studying the leisure patterns of 10-15 year old preadolescences, found that the indicator of social class was not related to the space of leisure activities. However, social class was related to the number of leisure appointments during week and weekend and to the organized leisure activities young people were involved in. Roberts et al. (2009)??? also found that the differences in leisure trajectories of young people in the South Caucasus from age 16 to 30 were widening due to the different social class trajectories they followed. Then, to find support to the *social age hypothesis*, we should find not only a relationship between young people patterns of leisure and age but also an interaction between age and young individuals social position. Not finding a meaningful interaction, the data  would support the  biological age hypothesis instead the social one.

Gender is another social category that seems to structure the space of culture, but findings are not convergent. Depending on the space of culture considered as well as the social context, findings suggest that women have developed a cultural taste that presupposes them towards the most social and established art and culture (Gallup 2011). That is, research has shown that leisure activities are gendered (Lamont and Fournier 1992 ???; Lamont et al. 1996; Bryson 1996; Katz-Gerro and Shavit 1998, Van Eijck 1997) even for young people (Zeijl et al 2001).  However, the findings are not generalizable due to variations in social and cultural spaces  (López-Sintas & García Álvarez 2002).  Notwithstanding, the development of a gendered cultural taste would depend on the specialization of roles developed in traditional  social settings: home for women, work for men. To find support to the specialization of gender roles hypothesis women have to be associated to a more social and legitimate art pattern of leisure than men. On the other hand,  the reproduction of the specialization of gendered roles is more often observed among underprivileged families. In consequence, we expect that the specialization of gender roles will be less manifest among young individuals holding privileged social positions. 

When researching the leisure of young people in an autonomous region as Catalonia  with two local languages (Catalan as well as Spanish) and a quarter of its young people speaking another language at home,  it seems necessary to take into account the relations of the language spoken at home with the leisure patterns of young people. Bourdieu (1984) has introduced the concept of the linguistic habitus that differs from the Chomskyan linguistic competence. The former is not the simple production of discourse, but a discourse that fits a particular context--a market or a field--that is socially acceptable according to the rules that organize interaction among individuals in a social context. The theory suggests that the linguistic habitus has a social value when language is used properly--with linguistic and social competence--, and then, and only then, the linguistic and social competence is transformed into what Bourdieu (1984) calls linguistic capital, and signals the social value of the persons that exhibit linguistic and social competence.

Young people develop at home the linguistic habitus needed to be socially competent in their social interactions outside home. Speaking the proper local language at home, young people can naturally associate the right linguistic competences to the proper social context. How competent they will be transforming their language competence into linguistic capital will depend on the variety of social interaction contexts they experiment during their childhood, and this, among other factors, depends on  the social position of their parents. To find support to Bourdieu's linguistic capital hypothesis we should find a relationship between young people patterns of leisure and the language spoken at home. Whether it is distributed equally among all social positions, it is an empirical matter.

#Research Design

##Data

Ordinary research into young people's  transitions--changes in their social status-- in their path to adulthood--labor market, academic credentials, forming a family, etc.--as well as into trajectories--long term patterns of stability and change--needs a longitudinal perspective. This study, instead, uses cross-sectional data in order to study the social structuration of young people leisure patterns. 

The data came from the  2012 Catalan Young People Survey, EJC12. It was a stratified two-stage sample: in the first stage municipalities were chosen, in the second, young people. Finally 3002 individuals, aged from 15 to 34, were personally interviewed at their homes, and the survey started on April 3rd , until August, 3rd (see Serracant 2013). Individuals were asked about their sociodemographic indicators as well as about their parents: education, labor activity, mobility, housing, leisure, social policy, language, health, and economic situation.

##Indicators of the leisure space

Young people interviewed were asked about the kind of leisure activities they normally do. Individuals were given a list of activities and they just had to choose among the options. The following  elections were possible: go clubbing (*gcl*), reading novels (*rnv*), playing sports (*spt*), nightlife (*nlf*), travelling outside Catalonia (*toc*), hicking tour (*hkt*), playing videogames (*pvg*), watching TV (*tv*), attending political events (*ape*), attending religious services (*ars*), going to the movies (*gmv*), going to the theatre (*gth*), going to dance, performances, opera or classical music (*gdoc*), going to concerts of modern music (*gcm*), studying (*std*), going to museums and exhibitions (*gmu*), being with friends on the street (*wfs*), staying with friends (*swf*), shopping (*shp*), walking (*wal*), reading traditional daly newspaper (*tnp*), reading digital daily paper (*dnp*), reading blogs (*rbl*), sensing and receiving e-mails (*email*), chanting (*chat*), using social networks (*snw*), watching internet media (*wim*), playing online games (*pog*), downloading movies (*dmv*), downloading music (*dms*), downloading games (*dvg*), downloading software (*dsw*). Descriptor are provided in Table 0.

##Social indicators

As indicators of social position we will use two indicators of education provided by the survey, the respondents’ education level as well as their father education level. In the former case, education levels was recorded into  4 categories: less than compulsory low secondary (*< ls*), compulsory low secondary (*ls*), high secondary (*hs*), university (*college*). Parent’s educations, instead, was coded as compulsory low education or less (*ls*), secondary education (*hs*), and university (*college*). Respondent’s occupation was recorded into managers (*managers*), technicians and professionals (*technicians*), occupations requiring an average qualification (*avequal*), occupations with out requiring a qualification (*lowqual*).

Language spoken at home was recorded into four categories: Catalan as well as Spanish (*CatSp*), only Spanish (*Sp*), other languages  (*other*). Age was recorded into four categories: 15-19 years (*a1*), 20-24 years (*a2*), 25-29 years (*a3*), 30-34 years (*a4*). Genre was recorded as male (*m*) & female (*f*).

Two indicators are used as controls: Region and city size. Region was recorded into 7 categories: Barcelona’s metropolitan area (*metropolitan*), counties of Girona (*girona*), counties of Tarragona (*tarragona*), countries of  *Terres de l’ebre* (*ebre*), counties of *Ponent and Alt Pirineu and Aran* (*altPririneu*), central counties *central*), *Penedès* (*penedes*). City size was recorded into four categories: less than 2000 inhabitants (*s2*), between 2001-10000 inhabitants, (*s10*), between 100001 and 50,000 (*s50*), more than 50,000, (*s50+*)

##Analysis

In order to test the hypotheses developed in the theoretical section, first we had to reduce the 32 leisure indicators into a few scales of leisure that would structure the space of leisure of Spanish young people. These scales of leisure are a measurement of the leisure habitus of our sample of young people, and would provide us with a set of scales with the proper properties for clustering individuals according to their patterns of leisure.

###Scales of leisure

To obtain a measurement of individuals leisure habitus we used multiple correspondence analysis, MCA, a procedure classified in the family of Geometric Data Analysis (GDA). MCA not only help us to reduce the dimensionality of the set of 32 leisure indicators but also the scales are the best measurement of leisure habitus (see Greenacre 1993 and Nishisato 1994).  MCA (Greenacre 1984, 1993) – also known as homogeneity analysis, HA (Nishisato 1994) – looks for the category scale values which lead to respondents’ scores maximally correlated with their scale values. This procedure allows us not only to reduce the 32 initial indicators, but also to interpret the scales as the measurement of leisure habits that explain the association we observe between the leisure indicators. Furthermore, with the scales we can form a space of leisure and explore their association with the original leisure indicators as well as with the position of individuals in the space according to their score in the scale.  These scales of leisure have the  optimal properties for clustering individuals according to their habits of leisure—uncorrelated and standardized.  

###Clustering individuals according to their patterns of leisure

After preprocessing categorical indicators with MCA and finding the individuals’ scores in the scales of leisure we proceeded to cluster individuals according to their patterns of leisure. This is a standard procedure for analyzing categorical indicators  (Lebart et al. 1984). For clustering individuals Lebart et al. suggest the complementary use of two numerical algorithms, first an agglomerative hierarchical clustering (as an aid to judge the sample heterogeneity and to decide the number of clusters into which partition the sample) and then a divisive algorithm for optimally dividing the sample into *k* clusters. However numerical algorithms usually fail to recover the actual patterns of behavior when the clusters do not have an spherical shape. For that reason we have used a mixture model strategy for clustering individuals that takes into account the actual shape of clusters (Fraley & Raftery 2002).

###Testing hypothesis

Finally, to test the hypotheses we used a model from the  multinomial logit family (Venables and Ripley 2002). We model the association between the set of pattern of leisure and the set of social position indicators as a multinomial model where the deterministic relationship is modeled according to a vector of social position indicators and a vector of parameters. The stochastic component, is modeled as an additive component that is identically and independently distributed according to the double exponential distribution.  Finally, the probability of classifying and individual in cluster *k* given his or her social position indicators is given by a multinomial logit model (Long 1997).

###Statistical computation 

The models have been estimated with *R: A Language and Environment for Statistical Computing* (R Core Team 2013). Specifically the MCA scales of leisure were estimated with the package *ade4* (Dray & Dufour, 2007). Individuals were clustered according to their  leisure patterns discovered with  the  *mclust* package that implements a model-based clustering procedure based on finite normal mixture modeling (Fraley, Raftery, Murphy, and Scrucca, 2012). Finally to test the hypothesis we used a multinomial logit model implemented in the *nnet* package  (Venables and Ripley 2002).

#Findings

##Leisure scales

The MCA conducted on the set of leisure indicators suggests that the first scale or axis (interpreted as a scale of leisure habits) explained the 59.8 % of the variation; the second, the 13,7%; and the third, the 4.1%; that is, the 77,6 % of the variation—-we have adjusted the variation explained as Greenacre (1993) suggests.  The decision of how many scales to retain for analysis depends on the scale’s contribution to the variance of the sample and on how easy it is to interpret the scale. In **Figure 1**, upper-left panel, it is easy to see that from the fourth scale on the increment in the variance explained was small and the scales were difficult to interpret. For that reason we have retained the first three scales or plot axes for forming the space of leisure and, later, clustering individuals.  The meaning of the leisure scales can be judge looking at their association with the original 32 leisure indicators.    

[Figure 1 around here]

To interpret the three scales of leisure as habits of leisure activities we have two aids: (1) the space of leisure formed by the three scales that play the role of axes in the two dimensional spaces shown in **Figure 1**, and (2) the contribution of each original indicator to the variance explained by each scale of leisure (**Table A1**). Both ways of interpretation should lead to the same meaning. 

In the space of leisure habitus the indicators nearer to the axes and placed further from the origin are the indicators that make a significant contribution to the axis variation they are nearest to. Unfortunately the visual inspection of the space of leisure is not clear enough when the indicators superpose--happens when one have many indicators--, for that reason we will make a complementary use of both aids. But first let’s see what the space of leisure tells us. 

Specifically, the first axis separates the negative answers to the indicators of leisure (see the upper-right panel of **Figure 1**) from positive answers (to the right in in that panel). The first scale captures a generic pattern of leisure activity (the indicators of labels are explained in the following paragraphs and in the appendix, **Table A1**). On the other hand, the second axis separates the indicators of culture activity (up in the same panel) from the other indicators of leisure activities (down). The third axis instead separates the indicators of social leisure (see down-left and down-right panels) from other leisure activities conducted at home, entertainment, especially digital leisure (see down-right panel). In summary, the first dimension is interpreted as the *scale of leisure activity*, the second, the *scale of cultural activity*, and the third separates the non cultural activity into *social leisure* and *recreation activity* (mainly digital leisure).

The interpretation of the space of leisure is consistent with the analysis of the contribution of each indicator to the axes variation (**Table A1** in the Appendix). Particularly, the indicators that make a contribution above the average and have a positive association to the first axis are the following activities: go clubbing (*gcl*) (in Table A1 the Y symbol means that the activity is done frequently or habitually), nightlife (*nlf*), going to the movies (*gmv*), going to concerts of modern music (*gcm*), being with friends on the street (*wfs*), read blogs or websites (*rbl*), check email (*email*), download movies (*dmv*), download music (*dms*), download games (*dvg*) and download software (*dsw*); the indicators that contribute significantly with a negative association are the following: do not go out at night, not studying, not staying with friends in the street, staying with friends, not to reading blogs, do not reading e-mail, no chatting, no downloading movies, and not downloading music. In short, the first scale captures a generic pattern of leisure activity.

The indicators that contribute significantly to the variation of the second axis, with a positive association, are the ones related to  the entertainment at home: Reading books (*rbl*), playing video games (*pvg*), playing  online (*pog*), downloading music (*dms*) and video games (*dvg*); in the other direction, with a negative association, the indicators of cultural leisure outside home: going to the theatre (*gth*), going to dance performances, opera and classical music (*gdoc*), going to concerts modern music (*gcm*), going to museums and exhibitions (*gmu*), travelling outside Catalonia (*toc*), and hiking (*hkt*).

On the other hand, the indicators that contribute significantly to the third axis and are positively associated are the indicators related to the social and relational leisure activities: go clubbing (*gcl*), having a nightlife (*nlf*), being with friends in the street (*wfs*), and chatting (*chat*) on the Internet; negatively associated are the indicators of entertainment activities performed at home: playing with video consoles (*pvg*), reading the daily newspapers on the internet (*dnp*), playing online (*pog*), downloading movies (*dmv*), games (*dvg*), and software (*dsw*). That is, this axis separates social  leisure activities from those performed for entertainment at home, especially the digital leisure activities.

##Clustering individuals according to their leisure patterns

We modeled the sample of individuals as a multivariate normal mixture model with *k* components. By default the package *mclust* (Fraley, Raftery, Murphy, amd Scrucca 2012) estimates models with 9 components and 10 covariance structures and provides the BIC values for all models (see Fraley, Raftery, Murphy, and Scrucca, 2012, pages 8 and 54 for further description).  *Table 1* includes the BIC values for models with 1 to 9 clusters (see the rows) and each cluster is modeled with up to ten different covariance structures.  In this case, the best model according to BIC is a 4 cluster model with ellipsoidal, but equal shape covariance, with 23 degrees of freedom, BIC -1073.205 (the maximum BIC is taken over all of the models and numbers of components considered).

[Table 1 around here]

Once identified the individuals that form each cluster we can represent them in the space of leisure. *Figure 2* shows the position of individuals in the space of leisure and their classification in the four patterns of leisure, and *Table 2* shows the mean values of the three leisure scales in the four clusters. The biggest cluster, 1, is situated in the negative side of the space of leisure formed with the first two scales—less leisure activities than the mean individual and a little bit more cultural than the mean individual, even though with values near to zero, but in the positive side of the third scale, the social leisure, indicating that the individuals classified in this cluster only have a social leisure habit superior to the mean and a cultural habitus superior to the mean. We call it the *social pattern of leisure*. Individuals in cluster 2 are placed to the right of the first axis—more leisure activities than the mean individual, but to the left part of axis 2 and 3, indicating that they do leisure activities that are cultural and recreational at home. We call it the *cultural omnivorous leisure pattern*. Individuals in cluster 3 have the higher pattern of leisure activity that it is characterized by entertainment leisure activities. We call it the *entertainment pattern of leisure*. Finally individuals in cluster 4 do less leisure activity than the mean profile, but the activity they do is attending to religious services. We call it the *religious pattern of leisure*.

[Table 2 around here]

In conclusion, the four patterns of leisure found suggest that a very large group, 46% of the population, has a social leisure pattern (go clubbing, playing sports, nightlife, attending religious services, studying, staying with friend in the street,staying with friends, shopping, walking, reading traditional newspaper, email, chatting, social networking, watching internet media). The second cluster of leisure has a cultural omnivorousness pattern: they do every thing except go clubbing, kicking, playing video games, watching tv, attending religious services, being with friends in the street, shopping, walking, chatting or playing online games. The third clusters has been named entertainment leisure pattern: go clubbing, sports, nightlife, playing video games, watching tv, going to the movies, with friend in the street, reading digital newspaper, reading blogs, playing online games, downloading everything. Finally, the fourth cluster has been named the religious pattern of leisure attending almost only to religious services.

[Figure 2 around here]

To complete the description of the four patterns of leisure in **Figure 3** we present the mosaic plot of the cross section distribution of the leisure patterns by the six individuals' social categories. Mosaic plots (Hartigan & Kleiner 1981 ???; Friendly 1994 ???) are a graphical method for visualizing the association between two or more categories. The association between the patterns of leisure and the genre of the individuals suggest that women have greater chances of  being found in the social and cultural patterns of leisure and men abound more in the recreational pattern.  According to the age, the chances of being classified in the religious cluster increases as individuals get older, and the chances of being classified in the recreational leisure pattern decreases as individuals get older, but the chances of being classified in the social and cultural clusters increases with age. 

As far as the education is concerned, the chances of being classified in the religious pattern of leisure is reduced as individuals are better educated, but the chances of being classified in the other three patterns, increases with the educational level. The relation between the patterns of leisure and the occupation follows a pattern similar to the one exhibited by the education.

The language spoken at home is also related to the leisure patterns: the chances of being classified in the religious pattern of leisure increases as families spoke only Spanish or other foreign languages at home; Individuals living in families speaking both Catalan and Spanish languages at home are the ones with better chances of being classified in the cultural pattern of leisure. Finally the association between the patterns of leisure and  parents educations follows the pattern exhibited by respondents' education, but the relationship is strongest for parents holding a college education: they exhibit the greatest association with the social and cultural patterns of leisure.

[Figure 3 around here]

##Leisure patterns and explanatory variables

###Test of hypothesis

To gain a better knowledge of the leisure pattern meaning we need to relate them to the explanatory variables in a way that could help us to test the hypothesis we have developed in the literature review.  We have to relate the set of social indicators to the patterns of leisure found but in the way predicted by the hypothesis developed. The relationship between the patterns of leisure and the set of hypotheses is examined using a multinomial logistic model. **Table 3** shows the model selection process we followed to test the hypotheses. We first estimated a base model with no effects, *M0*, and tested it against a model that takes into account the city-size and region, the two control variables (*M0b*). In *Table 3* the deviance is used to compare the two models with the likelihood ratio test, LR, and it suggests that the difference between the models deviances is statistically meaningful—the p-value of the Chi-square distribution of LR statistic is less than 0.001 (how ever, the AIC statistic favor model *M0*).

Against this model we tested the *biological age* and *gender hypotheses*, controlling for the effect of town-size and region, model *M1*. The indicators of age and gender are used to test the biological and gender hypotheses, respectively. The difference in models deviances are statistically meaningful again —AIC statistic also favor model *M1*. Then we proceed to test model *M1* against model *M2* that incorporates the *social age hypothesis*; to test this hypothesis *M2* model incorporates an interaction between biological age and an indicator of social position, concretely respondents education. If we find evidence that favor *M2*, this would suggest that leisure patterns of behavior would be influenced by the biological age (if still statistically meaningful), as well as by the social position of individuals, and the evidence favors model *M2*. In model *M3* we introduced an interaction between gender an respondents social position to test the *social gender hypothesis*, and the LR test as well as AIC statistic favor the *social gender hypothesis*. Finally,  in order to test the *linguistic capital hypothesis* we introduced an interaction between the language used at home and an indicator of fathers social position, educational level, in model *M4*. The evidence favors Model *M4*, suggesting that the impact of language on  leisure patterns was mediated by the social position of parents. 

[Table 3 around here]

###Parameters

**Table 4** describes the parameters for the final model, *M4*. Categorical variables are introduced in the model as dummy coding, in consequence we have to interpret parameters as variations in reference to the base category. As the parameters of a multinomial logistic model are expressed in relation to a based outcome, we have chosen the religious leisure pattern (cluster 4) as the based outcome. Then the effect of a one-unit change in a concrete variable, $\ X_{j}$, will have to be interpreted as its impact compared to the base outcome, the religious leisure pattern.  As the relative probabilities of each pair of  probabilities can be expressed as $\frac{Y_{i} } {Y_{i'} } = \frac{p_{i}(X, B)}{p_{i'}(X, B)}$,  but $\ B_{j}(i')$ is fixed to be zero in order to identify the model, then the relative probabilities due to a change of $\ X_{j}$ by one unit are premultiplied by $\frac{\exp(B_{j}(i))} {\exp(B_{j}(i'))} = \exp(B_{j}(i) - B_{j}(i'))$, however as $\ B_{j}(i')$ is zero to be able to identify the model, then the relative probabilities, $\frac{p_{i}(X, B)}{p_{i'}(X, B)}$, will change by $\exp(B_{j}(i))$.

[Table 4 around here]

###The biological age hypothesis versus the social age hypothesis

The final model suggest that the *biological age hypothesis* finds little evidence: the main effect of age is not statistically meaningful, so individuals could almost be classified in any leisure pattern irrespective of the age, even though  older individuals that are less probable to be classified in cluster 3 (*entertainment*) than in cluster 4 (*religious*), that is, young people are more probable to be classified in the social and cultural-omnivorous patterns of leisure but that differences are only statistically meaningful for the 30-34 age bracket).

Education, instead, is positively associated to the social, cultural/omnivorous and entertainment leisure patterns as shown un *Figure 3* (or negative related to the religious pattern of leisure). The interaction between age and education level is evidence that favor the *social age hypothesis*. The capacity of age to classify individuals in the four leisure patterns depends on individuals’ educational level: as the educational level gets higher, the  variation in probabilities of being classified in any cluster respect to being classified in the cluster of reference (*religious*) is negative, and the effect increases as individuals enjoy a high educational level.  In other words, the probability of being classified in the religious pattern of leisure increases with age for each educational level, and for with education for each age level.

*Social gender hypothesis*: compared to women, men are less probable of being classified in the entertainment and religious patterns of leisure, but the chances also depends on the educational level of individuals. That is, when taking into account educational level, gender differences are reduced, and  erased or even reversed for being classified in the social, cultural/omnivorous, and entertainment leisure patterns.

*Linguistic capital hypothesis*. The main effects of language suggests that speaking other languages at home increases  the probability of being classified in the religious pattern of leisure (reduces the probability of being classified in the other three patterns).  Parents education, how ever, reduces the chances of being classified in the entertainment and religious leisure patterns, and increases the probability of being classified in the cultural and social patterns of leisure. However, for families speaking other languages at home, parents’ college education increases the probability of being classified in the social pattern and reduces the probability of being classified in the religious patterns. This fits the association exhibit in *Figure 3*.

#Discussion

This research contributes to our knowledge of both the social structure of leisure practices as well as to the study of young people leisure activities. Since the 1970s research has hypothesized the existence of an homology between social practices and individuals’ social position.The sociology of culture, then, suggests that we should expect that the patterns of leisure be structured according to the individuals’ social position as well as their biological age. The shape of the homology, how ever, seems to have changed from a narrow but elitist set of practices and tastes (Bourdieu 1979)  towards an omnivorous pattern (Peterson and Simkus 1992 ???; Peterson and Kern 1996). 

According to our data and analyses the leisure activities conducted by young people have revealed a structure similar to the one reported by Le Roux et al. (2008) and Roose et al. (2012) when conducting research with a broad number of leisure indicators. That is, the association found among the indicators of practices can be explained first by an habitus of conducting leisure activities, second  by an habitus of conducting cultural activities, and lastly  the non cultural activities were related to a third scale that classifies them into a social or entertainment habitus. Research conducted by Zeijl et al. (2001) on the leisure patterns of preadolescents (10-15 year olds) reports similar habitus except for the cultural one: an habitus of producing leisure versus consuming leisure and a second habitus of practicing sports versus audiovisual engagement. Hersent (2003) reports similar findings for the youth between 6-17 year olds. 

From the position of individuals on the  three leisure habitus we have identified four young people leisure patterns. The four patterns can be described as having a social, cultural-omnivorous, entertainment or a religious pattern of leisure activities. Individuals classified in the social pattern were characterized by practicing most of the social leisure activities, but practicing the other activities less than the mean individual. The cultural omnivorous, on the other hand, were characterized especially by practicing most of the cultural leisure activities more than the average individual and by doing the other leisure activities more than the average individual or equal. The entertainment leisure patterns was characterized by individuals playing video-games, watching films in the computer screen, downloading music, etc. Finally, the religious leisure pattern showed a below the average pattern of conducting all leisure activities, except for attending to religious services.  The pattern of individuals hardly doing any leisure activity has being found in many pieces of research as well as the cultural and omnivorous pattern (Chan & Goldthorpe 2007a and b; van Rees et al. 1999; López & García 2002, 2006; Sintas & Álvarez 2004; Reeves 2014). 

The patterns of practices, however, depend on the specific domain of practices being studied, reading (van Rees et al 1999), going to libraries (Boter & Wedel 1999), performing arts (López & García  2005) and cinema (Chan & Goldthorpe 2005), listening music and going to other cultural activities (Chan & Goldthorpe 2005; López-Sintas & Katz-Gerro 2005; Tampubolon 2008a and b), outdoor cultural activities (López & García 2002); audiovisual practices (López & García 2006); visual arts (Chan & Goldthorpe 2007). 

Recent research, on the other hand, has put the emphasis not only on the role of capital (volume and composition) structuring the space of practices and tastes, but also on the role of age. Concretely, researchers have proposed that the indicators of individuals’ capital (volume and composition) as well as biological age are the main structuring factors of the space of practices and tastes (van Eijck 2001; López & García 2002a and b; Coulangeon 2003), and that both structure the space of practices and tastes orthogonally to each other (Tampubolon 2008a and b; López et al. 2014). 

In consequence, research so far  has supposed that the effect of social position indicators on practices and tastes does not depend on the biological age, that they are independent (Tampubolon 2008a and 2008b; López et al. 2014).  Yet, Bourdieu (1984) has argued that the effect of the biological age on young individual's patterns of practices and tastes is mediated by individuals’ social position. That is, if we do not take into account the role of individuals’ social position on young people leisure practices, biological age, Bourdieu (1984) argues, does not structure the practices of young people. 

We have found that young people leisure patterns are socially structured--the main respondents educations as well as parents education were statistically meaningful--but, as Bourdieu (1984) proposed, age does not structure young people leisure patterns if we do not take into account the mediating role of their social position. This finding qualifies the results reported so far that suggest that not only cultural capital and age are the main structuring factor of the space of practices, but that age stratifies  practices orthogonally to capital (Tampubolon 2008a and 2008b; López et al. 2014; Purhonen et al 2009; Savage 2006). As Bourdieu (1984) has suggested, young people apparently, but only apparently, form an homogeneous category: for that reason,  biological age does not accurately predict young people pattern of leisure.

That is, Bourdieu's' social age hypothesis has found support in the analysis: the biological age interacts with interviewees educational level, suggesting that the effect of age depends on social position as well as the effect of the latter depends on the former. That is, the relation of respondents' biological age with respondents' leisure patterns is mediated by their social position. Concretely, the effect of education on the chances of being classified in the social and cultural-omnivorous patterns of leisure is reduced as individuals get older, but are meaningful still. 

On the other hand, the social gender hypothesis also finds support. Even though the main effect of genre is statistically meaningful and men are positively related to the and social pattern of leisure, and negatively to the religious pattern, the main effect of genre was reduced or even vanished for all patterns of leisure when we take into account the education of respondents. This suggests that the leisure pattern of men and women are socially reproduced, that traditional families holding underprivileged social positions developed a gendered pattern of leisure activities; but modern families, in opposition, holding privileged social positions do not seem to develop gendered patterns of leisure. Zeijl et al (2000, 2001) report similar findings were repor

The social context from which the sample was taken gave us the opportunity to test Bourdieu's linguistic capital hypothesis. The analysis predicts that the main effect of language spoken at home, concretely speaking foreign languages at home increases the probability of being classified in the religious pattern of leisure, but interaction  of the language spoken at home with parents' educational level reduces the probability of being classified in the religious (increases the probability of being classified in the social pattern) for individuals whose parents have a college degree. 

Our findings have theoretical and methodological implications. The biological age does not seem to structure leisure practices orthogonally to social position. Although it seems that young people are an homogeneous social category, they aren't, the effect of biological age on social practices depends on individuals social position. Methodologically the findings   suggests that when researching the social structure of leisure practices of a sample of individuals with the complete distribution of biological age, we should test the mediation effect of individual social position on the leisure practices of each biological age. If the social age hypothesis finds evidence, then the generalizations from the main effects could be misleading. 

#Conclusion

This research contributes to our knowledge of both the social structure of leisure practices as well as to the study of young people leisure activities. To the former because not  only we have theorized why the indicators of social position may do not structure leisure practices orthogonally to age, but also we have presented evidence that when you take into account the mediating role of the indicators of social position the main effect age vanishes, as predicted by the *social age hypothesis*. To the study of young people patterns of leisure activities because we have shown that young people are not an homogeneous group, but that their leisure practices are still structured by social categories, like the *social gender hypothesis* and the *linguistic capital hypothesis*.  

#REFERENCES

Bennett, T., Savage, M., Silva, E. B., Warde, A., Gayo-Cal, M., & Wright, D. (2008). Culture, Class, Distinction. Taylor & Francis. 

Birchwood, D., Roberts, K., & Pollock, G. (2008). Explaining differences in sport participation rates among young adults: Evidence from the South Caucasus. European Physical Education Review, 14(3), 283–298. doi:10.1177/1356336X08095667

Bourdieu, P. (1979). La Distinction: Critique Sociale Du Jugement. Paris: Editions de Minuit.

Bourdieu, P. (1984). Questions de sociologie. Paris, FR: Editions de Minuit.

Bryson, B. (1996). “Anything But Heavy Metal”: Symbolic Exclusion and Musical Dislikes. American Sociological Review, 61(5), 884–899.

Bynner, J. (2012). Role statuses and transitions in adolescence and young adulthood: reflections and implications. Longitudinal and Life Course Studies, 3(2), 243–253.

Chan, T. W., & Goldthorpe, J. H. (2007a). Social stratification and cultural consumption: The visual arts in England. Poetics, 35(2-3), 168–190. doi:10.1016/j.poetic.2007.05.002

Chan, T. W., & Goldthorpe, J. H. (2007b). Social stratification and cultural consumption: music in England. European Sociological Review, 23(1), 1–19. doi:10.1093/esr/jcl016

Coulangeon, P. (2003). La stratification sociales des goûts musicaux. Revue Française de Sociologide, 44(1), 3–33.

Daenekindt, S., & Roose, H. (2014). Social mobility and cultural dissonance. Poetics, 42, 82–97. doi:10.1016/j.poetic.2013.11.002

Dray, S., & Dufour, A.-B. (2007). The ade4 Package: Implementing the Duality Diagram for Ecologists. Journal of Statistical Software, 22(4)(4). Retrieved from http://www.jstatsoft.org/v22/i04

Emmison, M. (2003). Social class and cultural mobility. Journal of Sociology, 39(3), 211–230.

Fraley, C., & Raftery, A. E. (2002). Model-Based Clustering, Discriminant Analysis, and Density Estimation. Journal of the American Statistical Association, 97(458), 611–631.

Fraley, C., Raftery, A. E., Murphy, T. B., & Scrucca, L. (2012). Mclust Version 4 for R: Normal Mixture Modeling for Model-Based Clustering, Classification, and Density Estimation. Technical Report No. 597, Department of Statistics, University of Washington.

George, L. K. (1993). Sociological Perspectives on Life Transitions. Annual Review of Sociology, 19(1), 353–373. doi:10.1146/annurev.so.19.080193.002033

Greenacre, M. J. (1984). Theory and Applications of Correspondence Analysis. London: Academic Press.

Greenacre, M. J. (1993). Correspondence Analysis in Practice. San Diego, CA: Academic Press.

Hersent, J.-F. (2003, January 1). Les pratiques culturelles adolescentes [Text]. Retrieved September 3, 2013, from http://bbf.enssib.fr/consulter/bbf-2003-03-0012-002

Katz-Gerro, T., & Shavit, Y. (1998). The Stratification of Leisure and Taste: Classes and Lifestyles in Israel. European Sociological Review, 14(4), 369–386.

Kuehn, T., & Witzel, A. (2000). Using a text databank in the evaluation of problem-centered interviews. FQS: Forum for Qualitative Social Research [On-line Journal], 3(1), [117 paragraphs].

Lamont, M., Schmalzbauer, J., Waller, M., & Weber, D. (1996). Cultural and moral boundaries in the United States: Structural position, geographic location, and lifestyle explanations. Poetics, 24(1), 31–56. doi:10.1016/0304-422X(96)00005-8

Lebart, L., Morineau, A., & Warwick, K. M. (1984). Multivariate Descriptive Statistical Analysis. New York: John Wiley & Sons.

Long, J. S. (1997). Regression Models for Categorical and Limited Dependent Variables. Thousand Oaks,CA: Sage.

López-Sintas, J., & García-Álvarez, E. (2002). Consumption of Cultural Products: An Analysis of the Spanish Social Space. Journal of Cultural Economics, 26(2), 115–138.

López-Sintas, J., & García-Álvarez, E. (2002). Omnivores Show Up Again: The segmentation of Cultural Consumers in the Spanish Social Space. European Sociological Review, 18(3, September), 353–368.

López-Sintas, J., & García-Álvarez, E. (2006). Patterns of audiovisual consumption: The reflection of objective divisions in class structure. European Sociological Review, 22 (4)(4), 397–411.

López-Sintas, J., Cebollada, À., Filimon, N., & Gharhaman, A. (2014). Music access patterns: A social interpretation. Poetics, 46, 56–74. doi:10.1016/j.poetic.2014.09.003

MacDonald, R., & Shildrick, T. (2007). Street Corner Society: Leisure Careers, Youth (Sub)culture and Social Exclusion. Leisure Studies, 26(3), 339–355. doi:10.1080/02614360600834826

Nagel, I. (2010). Cultural Participation Between the Ages of 14 and 24: Intergenerational Transmission or Cultural Mobility? European Sociological Review, 26(5), 541 –556. doi:10.1093/esr/jcp037

Nishisato, S. (1994). Elements of Dual Scaling. Hillsdale, NJ: Lawrence Erlbaum.

Peterson, R. A. (2007). Comment on Chan and Goldthorpe: Omnivore, what’s in a name, what’s in a measure? Poetics, 35(4-5), 301–305. doi:10.1016/j.poetic.2007.06.001

Peterson, R. A., & Anand, N. (2004). The Production of Culture Perspective. Annual Review of Sociology, 30(1), 311–334. doi:10.1146/annurev.soc.30.012703.110557

Peterson, R. A., & Kern, R. M. (1996). Changing Highbrow Taste: From Snob to Omnivore. American Sociological Review, 61(October), 900–907.

Pollock, G. (2008). Youth Transitions: Debates over the Social Context of Becoming an Adult. Sociology Compass, 2(2), 467–484. doi:10.1111/j.1751-9020.2008.00097.x

Pronovost, G. (2009). Le rapport au temps des adolescents: une quête de soi par-delà les contraintes institutionnelles et familiales. Informations sociales, n° 153(3), 22–28.

Pugh, A. J. (2011). Distinction, boundaries or bridges?: Children, inequality and the uses of consumer culture. Poetics, 39(1), 1–18. doi:10.1016/j.poetic.2010.10.002

Purhonen, S., Gronow, J., & Rahkonen, K. (2009). Social Differentiation of Musical and Literary Taste Patterns in Finland. Research on Finish Society, 2, 39–49.

R Core Team. (2014). R: A Language and Environment for Statistical Computing. Vienna, Austria: R Foundation for Statistical Computing. Retrieved from http://www.R-project.org/

Reeves, A. (2014). Neither Class nor Status: Arts Participation and the Social Strata. Sociology, 0038038514547897. doi:10.1177/0038038514547897

Roberts, K., & Pollock, G. (2009). New class divisions in the new market economies: evidence from the careers of young adults in post-Soviet Armenia, Azerbaijan and Georgia. Journal of Youth Studies, 12(5), 579–596. doi:10.1080/13676260903081640

Robinson, J. P. (2010). Arts and Leisure Participation Among IT Users: Further Evidence of Time Enhancement Over Time Displacement. Social Science Computer Review, 0894439310385643. doi:10.1177/0894439310385643

Roose, H., van Eijck, K., & Lievens, J. (2012). Culture of distinction or culture of openness? Using a social space approach to analyze the social structuring of lifestyles. Poetics, 40(6), 491–513. doi:10.1016/j.poetic.2012.08.001

Roux, B. L., Rouanet, H., Savage, M., & Warde, A. (2008). Class and Cultural Division in the UK. Sociology, 42(6), 1049–1071. doi:10.1177/0038038508096933

Savage, M. (2006). The musical field. Cultural Trends, 15(2-3), 159–174. doi:10.1080/09548960600712975

Shildrick, T., & MacDonald, R. (2006). In Defence of Subculture: Young People, Leisure and Social Divisions. Journal of Youth Studies, 9(2), 125–140. doi:10.1080/13676260600635599

Shildrick, T., Blackman, S., & MacDonald, R. (2009). Young people, class and place. Journal of Youth Studies, 12(5), 457–465. doi:10.1080/13676260903114136

Sintas, J. L., & Álvarez, E. G. (2004). Omnivore versus univore consumption and its symbolic properties: evidence from Spaniards’ performing arts attendance. Poetics, 32(6), 471–491. doi:10.1016/j.poetic.2004.08.001

Tampubolon, G. (2008). DISTINCTION IN BRITAIN 2001-2004? Unpacking homology and the “aesthetics” of teh popular class. Europena Societies, 10(3), 403–428.

Tampubolon, G. (2008). Revisiting omnivores in America circa 1990s: The exclusiveness of omnivores? Poetics, 36(2-3), 243–264. doi:10.1016/j.poetic.2008.02.007

The Gallup Organization. (2011). Youth on the move-Analytical Report (No. Flash EB Series #319a) (p. 60). Directorate-General Education and Culture, European comission.

Thomas W. Yee (2010). The VGAM Package for Categorical Data Analysis. Journal of Statistical Software, 32(10), 1-34. URL http://www.jstatsoft.org/v32/i10/.

Tolonen, T. (2013). Youth Cultures, Lifestyles and Social Class in Finnish Contexts. Young, 21(1), 55–75. doi:10.1177/1103308812467671

Van Eijck, K. (1997). The impact of family background and educational attainment on cultural consumption: A sibling analysis. Poetics, 25, 195–224.

Van Eijck, K. (2001). Social Differentiation in Musical Taste Patterns. Social Forces, 79(3), 1163–1185.

Van Rees, K., Vermunt, J., & Verboord, M. (1999). Cultural classifications under discussion latent class analysis of highbrow and lowbrow reading. Poetics, 26(5–6), 349–365. doi:10.1016/S0304-422X(99)00019-4

Venables, W. N., & Ripley, B. D. (2002). Modern Applied Statistics with S-Plus. New York: Springer-Verlag.

Virtanen, T. (2005). Dimensions of Taste for cultural consumption–A Cross-Cultural Study of Young Europeans. Turku, Finland.

Wuggenig, U. (2007). Comments on Chan and Goldthorpe: Pitfalls in testing Bourdieu’s homology assumptions using mainstream social science methodology: Social stratification and cultural consumption: The visual arts in England. Poetics, 35(4–5), 306–316. doi:10.1016/j.poetic.2007.06.002

Wyn, J., & Woodman, D. (2006). Generation, Youth and Social Change in Australia. Journal of Youth Studies, 9(5), 495–514. doi:10.10803676260600805713

Zeijl, E., Bois-Reymond, M. du, & Poel, Y. te. (2001). Young Adolescents’ Leisure Patterns. Loisir et Société, 24(2), 379. doi:10.7202/000188ar

Zeijl, E., Poel, Y. te, Bois-Reymond, M. du, Ravesloot, J., & al,  et. (2000). The role of parents and peers in the leisure activities of young adolescents. Journal of Leisure Research, 32(3), 281–302.

