---
output: word_document
---
**Table 4**: Multinomial Model (religious leisure pattern as the base pattern)
| -------------------------------------------------------------------- | ------------ | ----------- | ------------ |
|                                                                      | 1            | 2           | 3            |
| -------------------------------------------------------------------- | ------------ | ----------- | ------------ |
| Genre: Male                                                          | 2.365\***    | 2.174       | 0.760        |
| Education: LS                                                        | 3.550\***    | 4.804\**    | 1.545        |
| Education: HS                                                        | 5.931\***    | 6.274\***   | 3.037\**     |
| Education: College                                                   | 6.045\***    | 7.267\***   | 3.413\**     |
| SizeTown: 2001-10000                                                 | 0.223        | 0.584       | 0.559        |
| SizeTown: 10001-50000                                                | 0.259        | 0.523       | 0.462        |
| SizeTown: > 50000                                                    | 0.473        | 0.683\*     | 0.173        |
| Age: 20-24                                                           | 0.832        | -1.661      | -6.185       |
| Age: 25-29                                                           | -0.377       | -0.909      | -1.315       |
| Age: 30-34                                                           | 0.501        | 0.376       | -4.402\*     |
| Language: Catalan and Spanis                                         | -0.011       | -0.030      | 1.032        |
| Language: Spanish                                                    | 0.209        | 0.162       | 0.477        |
| Language: Other foreign languages                                    | -0.577\*     | -0.738\*    | -0.933**     |
| Parents Education: HS                                                | 0.818\**     | 1.245\***   | 0.736\**     |
| Parents Education: College                                           | 1.621\***    | 2.101\***   | 0.778*       |
| Region: Girona                                                       | 0.363        | 0.005       | -0.264       |
| Region: Tarragona                                                    | 0.173        | -0.078      | -0.183       |
| Region: Ebre                                                         | 0.223        | -0.045      | 0.182        |
| Region:Alt Pirineu                                                   | 0.120        | -0.088      | -0.210       |
| Region: Central                                                      | 0.139        | -0.376      | -0.705\*     |
| Region: Penedes                                                      | 0.618\**     | 0.361       | -0.242       |
| Genre: Male \* Education: LS                                         | -1.622\**    | -1.453      | 0.605        |
| Genre: Male \* Education: HS                                         | -2.991\***   | -2.269      | 0.925        |
| Genre: Male \* Education: College                                    | -1.710\**    | -1.599      | 1.447        |
| Education: LS \* Age: 20-24                                          | -2.846\**    | -0.682      | 3.587        |
| Education: HS \* Age: 20-24                                          | -3.715\***   | -1.131      | 3.057        |
| Education: College \* Age: 20-24                                     | -4.028\**    | -1.324      | 2.446        |
| Education: LS \* Age: 25-29                                          | -1.669       | -1.560      | -2.629\**    |
| Education: HS \* Age: 25-29                                          | -2.782\**    | -2.170      | -2.987\**    |
| Education:College \* Age: 25-29                                      | -3.615\**    | -3.116      | -3.974\**    |
| Education: LS \* Age: 30-34                                          | -3.128\***   | -3.385*     | -0.508       |
| Education: HS \* Age: 30-34                                          | -5.081\***   | -4.590\**   | -2.851       |
| EducationCollege: Age30-34                                           | -5.153\***   | -5.085\**   | -2.803       |
| Language: Catatalan & Spanish \* Parents Education: HS               | 1.044        | 1.173       | -0.740       |
| Language: Spanish \*  Parents Education: HS                          | -0.285       | -0.057      | -0.070       |
| Language: Other foreign languages                                    | 0.686        | 0.265       | -0.407       |
| Language; Catalan & Spanish \* ParentsEducationCollege               | 1.861        | 2.899\*     | 1.610        |
| Language: Spanish  \* Parents Education: College                     | -0.454       | -0.439      | 0.122        |
| Language: Other foreign languages \* Parents Education: College      | 1.601\**     | 0.776       | 2.167\**     |
| Constant                                                             | -1.732\*     | -3.921\**   | -0.168       |
\hline
| Akaike Inf. Crit.                                                    | 6,407.31     | 6,407.31    | 6,407.31     |

Note:                                    \*\ p<0.1;  \**\ p<0.05;  \***\ p<0.01

