---
title: "Table M4"
author: "Jordi López Sintas"
date: "12 de diciembre de 2014"
output: html_document
---

|                                                                    | 2 | 3| 4 |
|--------------------------------------------------------------------|----------|----------|----------|
| Genre: Male                             | -0.240      | -1.633 \*      | -2.387 \***|
|                                      | (1.423)|   (0.982)  | (0.631) |
|Education: LS                           |  1.305  | -2.010 \**   | -3.599 \*** |
|                                      | (1.784) |  (0.941)  | (1.036) |
|Education: HS                          |   0.403|   -2.897 \*** | -5.987 \*** |
|                                     |  (1.778) |  (0.928)  | (1.281) |
|Education: College                   |    1.280 |  -2.633 \*** | -6.118 \*** |
|                                     |  (1.772) |  (0.925)  | (1.452) |
|Education: HS                          |   0.403|   -2.897 \*** | -5.987 \*** |
|                                     |  (1.778) |  (0.928)  | (1.281) |
|Education: College                   |    1.280 |  -2.633 \*** | -6.118 \*** |
|                                     |  (1.772) |  (0.925)  | (1.452) |
|SizeTown: 2001-10000                 |    0.369 |   0.348  |  -0.212 | 
|                                     | (0.284)  | (0.369)  | (0.342) |
|SizeTown: 10001-50000                  | 0.273   | 0.216 | -0.249  |
|                                    |  (0.276) | (0.363) | (0.325) |
|SizeTown: > 50000                     |   0.219  | -0.285  |  -0.467  |
|                                      | (0.276)  | (0.368) | (0.336) |
|Age: 20-24                           |  -1.463  | -5.758 | -0.866 |
|                                    |  (2.549) | (5.067) | (0.990) |
|Age: 25-29                           |   -0.590 |   -0.892 |    0.361  |
|                                     | (2.007) | (0.972) | (0.853) |
|Age: 30-34                         |    -0.013  | -5.050* |  -0.542  |
|                                   |   (1.730)  | (2.771) |  (0.882) |
|Language: CatSp                   |      0.001 |   1.064**  | -0.003|  
|   Catalan and Spanish           |     (0.586)  | (0.474)  | (0.570) |
|Language: Spanish                 |     -0.047  |  0.270  | -0.209 |
|                                  |   (0.226)  | (0.211)  | (0.276) |
|Language:                        | -0.170  |  -0.358  |  0.571* | 
|   Other foreign languages      |     (0.308) |  (0.309)|   (0.297) |
|Parents Education: HS             |    0.427 \*  |   -0.079 |  -0.820 \**  |
|                                |   (0.222) |  (0.227) |  (0.320) |
|Parents Education: College         |  0.478 \**  | -0.843 \***  |-1.609 \***  |
|                                   |   (0.227) |  (0.300) |  (0.308) |
|Region: Girona                    |  -0.354 \*  | -0.621 \*** |  -0.372  |
|                                  |    (0.182) |  (0.236)  | (0.236) |
|Region: Tarragona                  |      -0.249|    -0.349  |  -0.176 | 
|                                    |   (0.188)  | (0.254) |  (0.268)| 
|Region: Ebre                         |-0.280 |   -0.053  |  -0.231 | 
|                                   |    (0.331)  | (0.381) |  (0.419) |
|Region:Alt Pirineu                  |  -0.203  |  -0.317 |   -0.128  |
|                                     |  (0.219)  | (0.289) |  (0.300) |
|Region: Central                       |  -0.511 \**   | -0.847 \**   | -0.144  |
|                                     |  (0.248)  | (0.337) |  (0.296) |
|Region: Penedes                        |  -0.257 |  -0.853 \***  |-0.623 \** | 
|                                      | (0.208)  | (0.286) |  (0.310) |
|Genre: Male \* Education: LS          |     0.220 |   2.252 \**  |  1.644 \** |
|                                   |  (1.433)  | (1.013) |  (0.657) |
|Genre: Male \* Education: HS           |     0.770 |  3.951 \***   | 3.018 \***  |
|                                 |   (1.434) | (1.006) | (0.683)|
|Genre: Male \* Education: College      |     0.161 |  3.188 \***  |  1.735 \**  |
|                                   |    (1.431) |  (1.007) |  (0.714) |
|Education: LS \* Age: 20-24          |      1.140 |    5.182  |  2.890 \**  |
|                              |    (2.571)  | (5.077)  | (1.188) |
|Education: HS \* Age: 20-24        |         1.553  |   5.512 |  3.76 1 \***  |
|                                |    (2.565) |  (5.073) |  (1.419)| 
|Education: College \* Age: 20-24      |    1.675  |   5.213  |  4.094 \**  |
|                                  |  (2.559)  | (5.073) |  (1.591) |
|Education: LS \* Age: 25-29           |     0.173 |   -1.006 |    1.695  |
|                                  |  (2.031)  | (1.039) |  (1.068) |
|Education: HS \* Age: 25-29            |  0.670  |  -0.257  |  2.811 \**  |
|                                    |  (2.027) |  (1.011) |  (1.320) |
|Education:College \* Age: 25-29        |    0.558  |  -0.408 |   3.661 \**  |
|                                    |  (2.021)  | (1.029) |  (1.493) |
|Education: LS \* Age: 30-34            |   -0.363  |   2.773 |  3.178 \*** | 
|                                    |  (1.755) |  (2.794) |  (1.085) |
|Education: HS \* Age: 30-34         |     0.378  |  2.366 |  5.133 \*** | 
|                                   |    (1.752) |  (2.804) |  (1.322) |
|EducationCollege: Age30-34      |    -0.045  |  2.490 |  5.224 \***  |
 |                             |      (1.746)  | (2.813) |  (1.498) |
|Language: Catatalan & Spanish    |    0.104 |  -1.807 \**   | -1.053  |
|     \* Parents Education: HS      |  (0.681)  | (0.720) |  (1.062) |
|Language: Spanish         | 0.228  |   0.212  |   0.283  |
|     \*  Parents Education: HS      |  (0.287)  | (0.299)  | (0.396) | 
|Language: Other foreign languages   |  -0.409  | -1.098 |  -0.676  |
|      \* Parents Education: HS    |  (0.467) |  (0.691)  | (0.502) |
|Language; Catalan & Spanish | 1.018  | -0.292   | -1.816 | 
|     \* ParentsEducationCollege   |   (0.653)  | (0.794) |  (1.415) | 
|Language: Spanish       |0.016   |  0.577  |   0.433 |  
|     \* Parents Education: College    |  (0.271)  | (0.354)|   (0.371) |
|Language: Other foreign languages  | -0.811 \*  |   0.560 |  -1.598 \**  |
|      \* Parents Education: College   |  (0.481) |  (0.735) |  (0.794) |
|Constant                        |    -2.256  |   1.548  |  1.768*  |
 |                                |   (1.792) |  (0.982) |  (0.912) |
|-----------------------------------|----------|--------|------------|
|Akaike Inf. Crit.                 |   6,407.31 | 6,407.31 | 6,407.31 |
|==================================|============|==========|=======|
Note:                                    \*\ p<0.1;  \**\ p<0.05;  \***\ p<0.01