---
title: "MCA Analysis "
output:
  pdf_document:
    highlight: tango
    fig_width: 7
    fig_height: 6
    fig_caption: true
    toc: true
    toc_depth: 4
    number_sections: true
---
```{r include=FALSE}
# Prepends general purpose libraries
source("../library.gnr/head.R")

# Requires libraries, installs if needed
fun.install.require(c("rmarkdown", "beepr", "ggplot2", "xtable", "ca", "ade4"))

# Loads module membership data generated by 03.cca.R
load("../data.gnr/cca.membership.Rdata")

# Loads the **mca** output generated by 04.mca.R
load("../data.gnr/mca.output.Rdata")

# Loads the list with different mca analysis for each cca module
load("../data.gnr/mca.module.output.Rdata")

# Loads the **mca.ade4** output generated by 04.mca.R
load("../data.gnr/mca.ade4.output.Rdata")

# Loads the list with different mca.ade4 analysis for each cca module
load("../data.gnr/mca.ade4.module.output.Rdata")

# Loads cca zero module
load("../data.gnr/cca.zeros.Rdata")

# Loads the music data
load("../data.gnr/music.Rdata")

# Different colors for each cca mudule
color <- c("red", "green", "blue")
```


# Summary

```{r, results='asis', warning=FALSE, echo=F, fig.width=9, fig.height=12}
# Tries to plot with GGPLOT2


# Plots overall genre space
cat("\n\n# MCA Analysis for All Observations \n\n")
plot(mca.output, what=c("active","active"), arrows=c(T,T), col = c("black", "grey"), contrib=c("absolute",F)
     , main="MCA - Genre Spaces - All Observations")

# Plots overall descriptors space
plot(mca.output, what=c("passive", "passive"), arrows=c(T,T), col = c("black", "grey")
     , main="MCA - Desc. Spaces - All Observations")
cat("\n\n \\pagebreak \n\n")

# Plots observations
s.class(mca.ade4.output$li, as.factor(cca.membership), cellipse = 2, col=color)

cat("\n\n# MCA Analysis for CCA Modules \n\n")

# for each cca module plot the mca graph
for(cnt.i in 1:length(levels(as.factor(cca.membership)))){
  # Makes the temp mca output variable for each cca module
  tmp.mca.output <- mca.module.output[[cnt.i]]
  tmp.mca.ade4.output <- mca.ade4.module.output[[cnt.i]]

  cat(sprintf("\n\n## CCA Module %s \n\n", cnt.i))

  # Plots genre space for cca modules
  plot(tmp.mca.output, what=c("active","active"), arrows=c(T,T), col = c("black", "grey")
     , main=sprintf("MCA - Desc. Spaces - Module %s", cnt.i))
  cat("\n\n \\pagebreak \n\n")

  # Plots descriptor space for cca modules
  plot(tmp.mca.output, what=c("passive","passive"), arrows=c(T,T), col = c("black", "grey")
     , main=sprintf("MCA - Desc. Spaces - Module %s", cnt.i))
  cat("\n\n \\pagebreak \n\n")

  # Plots observations
  s.class(tmp.mca.ade4.output$li, as.factor(rep(1, nrow(tmp.mca.ade4.output$li))), cellipse = 2)
}
```
