---
title: "Data Exploration"
output:
  pdf_document:
    highlight: tango
    fig_width: 7
    fig_height: 6
    fig_caption: true
    toc: true
    toc_depth: 2
    number_sections: true
---
```{r include=FALSE}
# rmar-own::render("02.data.exploration.Rmd")
source("../library/head.R")

fun.install.require(c("circlize","ggplot2","xtable"))

load(pth.music.rdata)

# fun.install.require("Hmisc")
# latex(describe(df.music))
arr.interest <- c("interest.clasicm","interest.concertam","interest.listenm","interest.music")
attach(df.music)
```

\newpage

# Interests

```{r, results='asis', echo=F, fig.width=10, fig.height=11}
  mat=table(interest.music, interest.concertam)
  rownames(mat) <- paste("intrest.music", rownames(mat),sep="\n")
  colnames(mat) <- paste("intrest.concertam", colnames(mat),sep="\n")
  print(chordDiagram(mat, directional = TRUE, transparency = 0.5))

  cat("\n\n")

  mat=table(interest.music, interest.listenm)
  rownames(mat) <- paste("intrest.music", rownames(mat),sep="\n")
  colnames(mat) <- paste("intrest.listenm", colnames(mat),sep="\n")
  print(chordDiagram(mat, directional = TRUE, transparency = 0.5))

  cat("\n\n")

  mat=table(interest.music, interest.clasicm)
  rownames(mat) <- paste("intrest.music", rownames(mat),sep="\n")
  colnames(mat) <- paste("intrest.clasicm", colnames(mat),sep="\n")
  print(chordDiagram(mat, directional = TRUE, transparency = 0.5))

  cat("\n\n")
```

```{r, results='asis', echo=F, fig.width=9, fig.height=5.5}
arr.groupby <- c("gender","age5", "occupaton5", "educ3")
for(cl in arr.interest){
  cat(sprintf("\n\n## %s \n\n", cl))
  print(xtable(t(table(df.music$interest.music))), type="latex", comment=F)
  cat("\n\n")

  for(gb in arr.groupby){
    gg <- ggplot(df.music, aes_string(x=sprintf("%s",cl))) +
    geom_freqpoly(aes_string(group = sprintf("%s",gb), colour = sprintf("%s",gb))) +
    ggtitle(sprintf("Frequency Polygraph of %s\nGrouped by %s", cl, gb))

    print(gg)
    cat(" \n\n ")
  }

#  print(ggplot(df.music, aes(x = cl, color = occupaton5)) + geom_density())
#  print(ggplot(df.music, aes(x = cl, color = age5)) + geom_density())
#  print(ggplot(df.music, aes(x = cl, color = educ3)) + geom_density())
}
```

